### ISSUE TITLE
Can't download/pull DB

### ISSUE THREAD

**Issue by tiberium-v** [baumrock/RockShell#19]
When I try the db:download / pull command, it can create on remote the backup, but failed to download it.

> [!NOTE]
>  The db:dump command on the other hand is functional and create a local db backup in the right folder.

> ╚ $ rockshell db:download
> Creating remote dump ...
> cd public_html &&       php RockShell/rock db:dump -f tmp.sql
>   Dumping database...
>   Root path: /usr/www/users/xxxxx/
>   File path: site/assets/backups/database/tmp.sql
>   Filesize: 356,6kB
> 
> 
> Copying dump to local ...
> /var/www/html//site/assets/backups/database/tmp.sql: No such file or directory
> 
> Removing remote dump ...
> 
> Download complete!

> ╚ $ rockshell db:pull
> Creating remote dump...
>   Remote path: public_html
>   Remote command: php RockShell/rock db:dump -f tmp.sql
>   Dumping database...
>   Root path: /usr/www/users/xxxxx/
>   File path: site/assets/backups/database/tmp.sql
>   Filesize: 356,6kB
> 
> 
> Copying dump to local...
> /var/www/html//site/assets/backups/database/tmp.sql: No such file or directory
> 
> Removing remote dump...
> 
> Dropping of all tables enabled.
> Restoring DB from tmp.sql ...
> Restore file does not exist: /var/www/html/site/assets/backups/database/tmp.sql
> 

I notice the wrong double slash on the local folder, so I changed /App/Commands/DbDownload.php:70 and remove the beginning slash before the $folder variable, so it looks like that:

`$this->exec("scp $ssh:$dir/$folder/tmp.sql {$wire->config->paths->root}/$folder/tmp.sql");`

Then the output will show the correct path inside the ddev container, but still fail with the same message.

Environment:

- DDEV  v1.24.1
- PHP 8.3 (inside ddev and remote)
- ProcessWire 3.0.242 

I checked also the ddev working dir, and that looks right with the output of RockShell

**Comment by BernhardBaumrock** [comment]
Thx @tiberium-v I have pushed a fix for this on the dev branch. I don't have problems now and it works as expected. Not sure why it does not work for you? Could you please try again?

**Comment by tiberium-v** [comment]
Hi, unfortunate not. I downloaded the dev branch and activate the verbose mode

> ╚ $ rockshell db:download -vvv
> Creating remote dump ...
> cd public_html &&       php RockShell/rock db:dump -f tmp.sql
> ssh xxx@dxxxde -p222 "cd public_html &&       php RockShell/rock db:dump -f tmp.sql"
>   Dumping database...
>   Root path: /usr/www/users/xxx/
>   File path: site/assets/backups/database/tmp.sql
>   Filesize: 1,2MB
> 
> 
> Copying dump to local ...
> scp xxx@dxxx.de -p222:public_html/site/assets/backups/database/tmp.sql /var/www/html//site/assets/backups/database/tmp.sql
> /var/www/html//site/assets/backups/database/tmp.sql: No such file or directory
> 
> Removing remote dump ...
> ssh xxx@dxxx.de -p222 "cd public_html && rm -rf public_html/site/assets/backups/database/tmp.sql"
> 
> Download complete!

I still see the double slashes in the target path of the ddev environment. What I have to added is, that the tmp.sql is created successful. But it didn't get deleted on the remote server.

You see in the last scp row, it goes first via cd in the public folder and then send the rm-rf but with the path of the public_folder again.

A maybe important info, I'm running linux. Maybe there is something in the script that get's handle different on Mac/Win?

My config (maybe I did something wrong here):
```php
$config->rockshell = [
  // optional: use different php version
  // 'remotePHP' => 'keyhelp-php81',
  'remotes' => [
    'staging' => [
      'ssh' => 'xxx@xxx.de -p222',
      'dir' => 'public_html',
    ],
    // 'production' => [
    //   'ssh' => 'user@host.com',
    //   'dir' => '/path/to/your/site/current',
    // ],
  ],
];
```

**Comment by BernhardBaumrock** [comment]
Hey @tiberium-v this should be fixed in v3.5.3 🥳

**Comment by tiberium-v** [comment]
Hey, 
sorry for the long delay, there was no new project with it in between. I tested today and it works flawless now.

Thank you for fixing!
